# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016)], default=2016, verbose_name='Year')),
                ('semester', models.CharField(choices=[('WS', 'Winter'), ('SS', 'Summer')], default='WS', max_length=2, verbose_name='Semester')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pkz',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Personal Identification Number'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='base.Course'),
        ),
    ]
