# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Movie')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('released', models.DateField(verbose_name='Release date')),
                ('poster', models.ImageField(upload_to='')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Movie')),
                ('released', models.DateField(verbose_name='Release date')),
                ('poster', models.ImageField(upload_to='')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('genres', models.ManyToManyField(to='web.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Movie')),
                ('poster', models.ImageField(upload_to='')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('genres', models.ManyToManyField(to='web.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Serie'),
        ),
    ]
