# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 08:05
from __future__ import unicode_literals

import campus02.base.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_auto_20160908_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchListMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('watched', models.DateTimeField(blank=True, null=True, verbose_name='Watched')),
            ],
        ),
        migrations.RemoveField(
            model_name='episode',
            name='poster',
        ),
        migrations.AddField(
            model_name='genre',
            name='tmdb',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='homepage',
            field=models.TextField(blank=True, null=True, verbose_name='Homepage'),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Runtime'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.TextField(blank=True, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=campus02.base.utils.RandomFileName()),
        ),
        migrations.AlterField(
            model_name='serie',
            name='poster',
            field=models.ImageField(upload_to=campus02.base.utils.RandomFileName()),
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Movie'),
        ),
        migrations.AddField(
            model_name='watchlistmovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
