# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160916_0805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchListMovie',
            new_name='Watchlist',
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'permissions': (('view_watchlist', 'View watchlist'),)},
        ),
    ]
