# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rating_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'permissions': (('view_resume', 'View resume'),)},
        ),
    ]
