# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0007_auto_20160929_1959'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resume',
            unique_together=set([('user', 'movie')]),
        ),
    ]
