# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20160930_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='genres',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'get_latest_by': 'released', 'ordering': ['title']},
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
