# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'permissions': (('view_history', 'View history'),)},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'permissions': (('view_rating', 'View rating'),)},
        ),
    ]
